packages:
  - '.'

blockExoticSubdeps: true
engineStrict: true
minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true

allowBuilds:
  esbuild: true

overrides:
  '@csstools/css-color-parser': 4.2.0
  '@csstools/css-syntax-patches-for-csstree': 1.1.8
  '@sveltejs/kit': 2.70.3
  cookie: 0.7.2
  nanoid: 3.3.18
  postcss: 8.5.26
  tldts: 7.4.10
  tldts-core: 7.4.10
  vite: 8.2.2
